### ISSUE TITLE
ADLoggerCallback isn't giving additional information

### ISSUE THREAD

**Issue by ashrat07** [AzureAD/azure-activedirectory-library-for-objc#1169]
`ADLoggerCallback` isn't returning any of the logger information like `additionalInfo`, `errorCode`, `userInfo` which we were receiving earlier in `LogCallback`. We use it for debugging purposes for dev/stage builds. Is there a reason behind doing this?

**Comment by oldalton** [comment]
We deprecated the old logger callback and added new API, which allows to track if log has any PII.

```
typedef void (^ADLoggerCallback)(ADAL_LOG_LEVEL logLevel,
                                 NSString *message,
                                 BOOL containsPii);

+ (void)setLoggerCallback:(ADLoggerCallback)callback;
```

"additionalInfo" in the old callback will still be sent, but only for messages actually containing PII. 

However, logging PII is now disabled by default, that's why you're probably not seeing any additionalInfo in the callback. To enable PII logging, use this API:

```
/*!
 ADAL provides logging callbacks that assist in diagnostics. There is a boolean value in the logging callback that indicates whether the message contains user information. If piiEnabled is set to NO, the callback will not be triggered for log messages that contain any user information. By default the library will not return any messages with user information in them.
 @param piiEnabled     PII on/off flag.
 */
+ (void)setPiiEnabled:(BOOL)piiEnabled;
```

Please, keep in mind, if you enable PII logging, you're responsible for handling PII properly.

Regarding additionalInfo and errorCode, the reason for not bringing those over into new callback, is maintainability and responsibility of logging. Mostly, errorCode in the logger callback would be either the same as the code returned by ADAL or missing and provided little diagnosability benefit. Please let me know what are your thoughts on that.

**Comment by ashrat07** [comment]
Is there a workaround where I can still get the `errorCode` and/or `additionalInfo`?

**Comment by oldalton** [comment]
Hi

As I explained above additionalInfo should still be sent in the old callback if piiEnabled is YES. 
As far as errorCode is concerned, you can get it from the ADAuthenticationResult. You currently can't get errorCode or additionalInfo in the logger callback anymore. 

If you have a scenario, which you can't solve without errorCode in the logger callback, please let me know. We can always make adjustments based on developer feedback :)

**Comment by oldalton** [comment]
I'll close this issue. Please feel free to reopen it, if it's still a problem.
