### ISSUE TITLE
Acquire token error: Failed to set item into keychain

### ISSUE THREAD

**Issue by pvroosendaal** [AzureAD/azure-activedirectory-library-for-objc#1280]
ADAL version 2.7.0 returns error 'Failed to set item into keychain.' when performing acquireToken(), so all of our users are unable to login with this version.
Rolling back to version 2.6.5 fixes the issue.

So far we tested on iOS 12 GM (iPhone 6 & X), and 11.4.1 (iPhone X).

**Comment by oldalton** [comment]
Thanks for reporting this. Can you please confirm, which keychain access group you're using (if any)? Thanks

**Comment by oldalton** [comment]
@pvroosendaal, I did some more testing on different ways to set keychain access group in ADAL and all the tests succeeded on 2.7.0.

Here's the list of tests:
1. Default access group
2. Send custom shared group when creating context
3. Send nil shared group when creating context
4. Override shared group through ADAuthenticationSettings
5. Set nil group through ADAuthenticationSettings
6. Provide custom group through ADKeychainTokenCache
7. Set nil custom group through ADKeychainTokenCache

All the tests behaved as expected on iOS 12GM. 

Therefore, can you please provide detailed answers to following questions?
1. What is the error you're seeing in the logger output, you should see something like:

`Failed to set item into keychain (status: ???)`

2. Are you setting any custom or nil access group through

`[ADKeychainTokenCache setDefaultKeychainGroup:@"com.access.group"];`

3. Are you setting any custom or nil access group through

`[[ADAuthenticationSettings sharedInstance] setDefaultKeychainGroup:@"test"];`

4. Are you setting any custom or nil access group when creating ADAuthenticationContext:

```
[[ADAuthenticationContext alloc] initWithAuthority:authority
                                                                        validateAuthority:validateAuthority
                                                                              sharedGroup:**@"mycustomgroup"**
                                                                                    error:&error];
```

5. If you're not doing any of those, which access groups do you have declared in your apps entitlements?

Thanks and looking forward to your responses.

**Comment by pvroosendaal** [comment]
Hi Olga, thanks for your response. We have a keychain access group set in the entitlements file ($(AppIdentifierPrefix).roadmap_access_group), but we're not using it for SSO and haven't set it in anyway with ADAL. In previous versions we never had to do that.
The error output only says "Failed to set item into keychain.". I don't see the 'status'.

**Comment by oldalton** [comment]
@pvroosendaal If you're not using default keychain sharing group for ADAL, you must call the following line:
`[[ADAuthenticationSettings sharedInstance] setDefaultKeychainGroup:nil];`

Otherwise, it will call "com.microsoft.adalcache" by default and it will fail (also in previous versions). 
Can you please confirm that you're doing that?

Regarding the difference between 2.6.5 and 2.7.0, maybe it's not handling the additional "." well in your access group, because it shouldn't be there.... I'll test that scenario and let you know.

**Comment by oldalton** [comment]
@pvroosendaal I figured out your issue. Basically, it seems that you also had issues in 2.6.5, they weren't just obvious. 

It looks like you don't change the default access group as per our documentation (you have to set it to nil), so ADAL will try to use "com.microsoft.adalcache" by default. 

Because you don't have "com.microsoft.adalcache" as one of your entitlements, any cache writing will fail. Next time when you'll try to use acquireTokenSilent, you will get AD_USER_INPUT_NEEDED error in 2.6.5. This will result in a very bad user experience, because there will be essentially no cache.

In 2.7.0, if we fail to write to the keychain, we return the error to the developer and we don't return the access token. 

Now, we'll discuss if we should change the behavior back to "failing silently" and still returning token, but essentially having no cache in the next version. 

As a workaround, please call this code prior to using ADAL:

`[[ADAuthenticationSettings sharedInstance] setDefaultKeychainGroup:nil];`

or pass nil sharedGroup when creating ADAuthenticationContext:

```
[[ADAuthenticationContext alloc] initWithAuthority:authority 
                                       validateAuthority:validateAuthority
                                       sharedGroup:nil
                                       error:&error];
```

This will ensure the best user experience for your users and should unblock you in 2.7.0. Please let me know if those workarounds help or if you have any additional questions.

**Comment by imranhhs** [comment]
Thanks, @oldalton its working fine now with above-mentioned API.

Error Details:
The operation couldn’t be completed. (Keychain ErrorDomain error -34018.)

**Comment by oldalton** [comment]
I believe this issue has been resolved. Feel free to reopen if you're still experiencing it in the latest ADAL version.

**Comment by pvroosendaal** [comment]
Thank you very much @oldalton ! This works indeed. I'm curious what the outcome of your discussion about "failing silently" will be. Please let me know If you find the time.

**Comment by oldalton** [comment]
We decided that failing early and clearly (like ADAL 2.7.x does) is better than failing silently and never caching any tokens. Cache is an essential component of ADAL. So, we will keep this as is.

However, in future we'll look into offering in-memory caching to not require caching to the keychain.
