### ISSUE TITLE
ADAL Multi Resource Refresh Token Error

### ISSUE THREAD

**Issue by harishios** [AzureAD/azure-activedirectory-library-for-objc#1315]
* Expected behavior 
     Aquire Access Token for **ResourceB** with Refresh Token of **ResourceA** should be providing Access Token for  **ResourceB** using the `acquireTokenWithRefreshToken` API.
     
* Actual behavior
      Aquire Access Token for **ResourceB** with Refresh Token of **ResourceA** results in 

> Your device is required to be managed to access this resource

* Steps to reproduce the problem
  
1. Call  `acquireTokenWithResource` with the resource as ResourceA then save the `accessToken` and `refreshToken` 
2. Call `acquireTokenWithRefreshToken` with the resource as ResourceB - `refreshToken` and Resource as ResourceB
3. Here it throws error saying,
`ERROR: Error raised: (Domain: "ADOAuthServerErrorDomain" Code: AD_ERROR_SERVER_REFRESH_TOKEN_REJECTED ProtocolCode: "interaction_required"`
 `Your device is required to be managed to access this resource.`

**_But the device is Under Compliance._** 

* Specifications like the version of the library, operating system etc.
ADAL 2.6.5 iOS 11.2.5

Note: The ResourceA `acquireTokenWithResource` response has `accessToken` and `refreshToken` but the `isMultiResourceRefreshToken()` is coming as **FALSE** - issue is because of this, if yes how could I solve this one?

ResourceA - [Yammer](https://www.yammer.com)
ResourceB - [Graph](https://graph.microsoft.com)

**Comment by oldalton** [comment]
@harishios Can you check the response for the first response from the server? (Please replace actual token contents with some dummy data)

**Comment by harishios** [comment]
Hi @oldalton : You want me to copy paste the response here?

**Comment by oldalton** [comment]
Yes, but please replace the token and resource values with dummies.

**Comment by harishios** [comment]
@oldalton 

tokenCacheItem.refresh_token = "dshjhj",
tokenCacheItem.access_token = "sdfdsfds",
tokenCacheItem.isMultiResourceRefreshToken() = false

**Comment by harishios** [comment]
@oldalton 

When I remove the MS Authenticator application, I was forced to login with the IN APP Browser and after giving the credentials I'm landing in to this page.

![img_0060](https://user-images.githubusercontent.com/18008999/46821628-3d5aa680-cd57-11e8-842b-6cff9c9ab2c0.PNG)

**Comment by oldalton** [comment]
Basically, the second resource that you're trying to use requires device to be compliant. If it's a third party app, brokered authentication through Authenticator app is required to support those policies. 

What you can do is:
1. acquireTokenWithResource with ResourceB through Authenticator
2. acquireTokenWithResource with ResourceA and prompt behavior PROMPT_AUTO will acquire token silently using existing cache.

Keep in mind, acquireTokenWithRefreshToken is not meant to be used the way you're using it. It's only meant for migration scenarios from your own authentication implementation to ADAL so that you can do a one time import of the refresh token silently. For any other scenarios, you should be using acquireTokenWithResource or acquireTokenSilentWithResource.

**Comment by harishios** [comment]
Hi @oldalton, Thanks for your response, in my case it's not sure that all the users will be having an Authenticator, and I also I can that Device is In Compliance.

**Comment by harishios** [comment]
@oldalton As I mentioned earlier, the two resources will be 

[https://graph.microsoft.com/](url) and [https://www.yammer.com/](url)

**Comment by oldalton** [comment]
@harishios If it's not a Microsoft first party app, brokered authentication is required to access compliant resources.

**Comment by harishios** [comment]
@oldalton Thank you for you detailed explanation! 

One last question, So without **MS Authenticator** application we can't access the multiple resources at same time correct?

**Comment by oldalton** [comment]
@harishios, ADAL SDK is used by both internal Microsoft products and external apps. If your app is not internal Microsoft product, then it's not a first party app. 

And no, you CAN access multiple resources without MS Authenticator app, BUT you CANNOT access any policy protected resources without MS Authenticator app. You have setup a policy for your second resource to require compliant device, that's why the request is failing. If you disable the policy, it should work. If the policy needs to be enabled, MS Authenticator app is necessary.

**Comment by harishios** [comment]
@oldalton Thanks for explaining why the request is failing, so now how to disable policy ? Any document link? How do we know that there is a policy defined for my second resource ? (Graph )

**Comment by oldalton** [comment]
You can change policy configurations in [azure portal](http://portal.azure.com).
Exact steps will depend on your configuration.

**Comment by oldalton** [comment]
I believe this issue has been resolved. Feel free to reopen if you have more questions.
