### ISSUE TITLE
ADAL cache not cleaning up

### ISSUE THREAD

**Issue by bullsseye** [AzureAD/azure-activedirectory-library-for-objc#1424]
In the logout functionality of my application, I have included the following statements:

```
ADKeychainTokenCache.keychainCache(forGroup: keychainAccessGroup).removeAll(forClientId: clientId, error: &error)

let storage = HTTPCookieStorage.shared
guard let cookies = storage.cookies else {
  return
}
for cookie in cookies {
  storage.deleteCookie(cookie)
}
```

But while login, adal is somehow giving the access token back.

**Some more details:**

**Clear Cache Scenario**
while debugging, it is successfully reaching the code point in ADAL where it is removing the cacheItem s. 
Inside MSIDLegacyTokenCacheAccessor clearCacheForAccount:clientId:context:error where it gets correct cacheItems (i.e accessToken and refreshToken) to remove and removes it successfully by returning YES. 

**Login scenario after clearing cache**
Inside MSIDLegacyTokenCacheAccessor in the first attempt refreshToken is returned nil from the cache but it then loops into _otherAccessors(I have checked the otherAccessor which is returning refreshToken is MSIDDefaultTokenCacheAccessor) where it gets the refreshToken. From this refreshToken, it calls the api to get the accessToken and it works. 
**To fix the above, I tried to remove the cache from default cache group on top of the specific cache group but still it does not work.**

**Comment by oldalton** [comment]
Thanks for reporting this. Can you please confirm which ADAL version are you seeing this with? We have had issues like that in earlier 2.7.x versions that got fixed. Thanks!

**Comment by andrejacobs** [comment]
I can confirm I am having a similar issue where removing all tokens for a client ID does not remove them.
Originally I developed my login feature using ADAL 4.0 and never had a problem with clearing the tokens. Then I had to switch to 2.7.x to allow Intune MAM SDK to work.

When I am not using Authenticator app (i.e. it is not installed on the device) and using ADAL 2.7.9 (or 2.7.12) then the tokens are not cleared.

I use the following code for removing the tokens:

ADKeychainTokenCache.defaultKeychain().removeAll(forClientId: clientId, error: &error)

The return value is true and there is no Error returned.

To confirm the tokens are cleared (based on a reply @oldalton did for a previous issue), I loop through:

ADKeychainTokenCache.defaultKeychain().allItems(nil)

And receive no tokens. So this part seems to work. However the next time the user wants to login,
the following method on the context:

acquireTokenWithInputIfRequired(for: resourceURI, clientId: clientID, redirectUri: redirectURI)

Briefly brings up the ADAL view controller and dismisses it immediately and the completion handler receives a valid token and thus my user can still login afterwards.

**Comment by andrejacobs** [comment]
Oh can I also just add, that when I use ADAL 4.0 again, this issue no longer happens.
Unfortunately for me I do have certain configurations of my application that require Intune MAM which at this point in time is not supporting ADAL 4.x yet.

**Comment by andrejacobs** [comment]
@oldalton This issue seems to only be a "in memory" issue. For example I can logout, login (with the bug of getting a token) many times in a row. However if I quit the app after a logout, then the next login does ask for details as I would expect.

**Comment by oldalton** [comment]
@andrejacobs, based on the behavior that you're describing, it's not token cache causing this issue. 

You mentioned above:

> Briefly brings up the ADAL view controller and dismisses it immediately and the completion handler receives a valid token and thus my user can still login afterwards.

If ADAL presents web view, it means there were no tokens in cache and it went to authorize endpoint instead. The behavior you're describing happens when there're cookies present instead. Cookies are normally stored only for the period that the process is running, that's why you're seeing that the issue is gone after application restart. 

Unfortunately, cookies is not something we control ourselves, and we also don't remove cookies on "signout", because there might be multiple signed in users, or app might rely on cookies being present.

ADAL 4.0 and 2.7 behaves a bit differently around session-only cookies, because of different web views used (AAD generally sets session-only cookies when ADAL/MSAL and embedded web view is used).

**ADAL 2.7**: Uses UIWebView. UIWebView cookies are accessible and removable through NSHTTPCookieStorage.

**ADAL 4.x**: Uses WKWebView. Session-only cookies are generally removed when new instance of WKWebView is created - that's unless web views used a static instance of WKWebViewConfiguration (that uses a shared process pool and data store). ADAL itself shares same instance of configuration internally to provide maximum SSO while the app is running. Application can provide their own webview to ADAL and configure their own configuration (or decide to use default one), which will have an indirect impact on cookies behavior. WKWebView provides its own cookie removal APIs (see example here: https://stackoverflow.com/questions/31289838/how-to-delete-wkwebview-cookies). NSHTTPCookieStorage won't have any impact on WKWebView cookies.

**Comment by andrejacobs** [comment]
@oldalton Thank you very much! I can confirm that if I delete all session cookies on logout, then this issue doesn't happen any more.

**Comment by mahmutpinarbasi** [comment]
Deleting session cookies & removing `WKWebsiteDataStore` data is not enough if application is not restarted in my case. Also removing `URLCache`'s cached responses solve it on __ADAL 4.x__

**Comment by thejaa** [comment]
Using ADAL (4.0.4) 
@mahmutpinarbasi  Deleted session cookies , removed WKWebView data and URLCache still Logout not working (i.e with out asking details it is navigating to next screen).

However if I quit the app after a logout, then the next login does ask for details as I would expect.

// Removing URLCache
URLCache.shared.removeAllCachedResponses()

// Removing WKWebview
extension WKWebView {
    func cleanAllCookies() {
        HTTPCookieStorage.shared.removeCookies(since: Date.distantPast)
        WKWebsiteDataStore.default().fetchDataRecords(ofTypes: WKWebsiteDataStore.allWebsiteDataTypes()) { records in
            records.forEach { record in
                WKWebsiteDataStore.default().removeData(ofTypes: record.dataTypes, for: [record], completionHandler: {})
                print("Cookie ::: \(record) deleted")
            }
        }
    }
    func refreshCookies() {
        self.configuration.processPool = WKProcessPool()
    }
}

// Removing ADKeychainTokenCache
ADKeychainTokenCache.defaultKeychain().removeAll(forClientId: clientID, error: nil)

// Deleting HTTPCookie
  _ = HTTPCookie.self
           let cookieJar = HTTPCookieStorage.shared

           for cookie in cookieJar.cookies! {
               cookieJar.deleteCookie(cookie)
           }

**Comment by mahmutpinarbasi** [comment]
Hey @thejaa,
I updated my comment.

**Comment by thejaa** [comment]
@mahmutpinarbasi  Thanks it's working grate.
