### ISSUE TITLE
Blank Login screen visible using ADAL library in iOS

### ISSUE THREAD

**Issue by manojchandola** [AzureAD/azure-activedirectory-library-for-objc#1476]
When we are login WAAD authentication using ADAL library with valid clientId, redirectURI and resourceId, blank login screen is visible with activity indicator(attached screen shot) . 
When we are trying to use the same login authentication url (which is generated by the ADAL library) on mobile safari browser, it open the Microsoft login page. 

Can you please help me to troubleshoot the issue.

![Image-1](https://user-images.githubusercontent.com/5878848/66545240-e2b97d80-eb57-11e9-9aa9-3c65cf0a584a.jpg)

**Comment by oldalton** [comment]
@manojchandola, can you please provide ADAL logs? Do you know if your environment requires certificate based authentication? Also, can you let me know your ADAL version and iOS version?

**Comment by manojchandola** [comment]
We are not getting any logs for that, it just stuck with activity indicator.
No, we don't require any certificate based authentication.
ADAL version 2.2 and iOS 13.

One more point need to mention: mobile phone is connected with the VPN, and that time we face this issue. But safari browser is loading that URL in VPN environment(mentioned below)
**https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=<Enter client ID>&resource=<Enter resource Id>&redirect_uri=<Enter Redirect URL>&state=YT1odHRwcyUzQSUyRiUyRmxvZ2luLndpbmRvd3MubmV0JTJGY29tbW9uJnI9aHR0cCUzQSUyRiUyRnNlcnZlci5ueG9uZS5jb20&x-client-CPU=32&x-client-DM=iPhone&x-client-Ver=2.6.5&x-client-SKU=iOS&x-client-OS=13.0&prompt=refresh_session&haschrome=1&client-request-id=C20C3C92-9108-2CB2-AC52-862C02379AC2**

**Comment by himanthmaddi** [comment]
Having same issue. We don't require any certificate based authentication.
ADAL version 2.7.15 ans iOS 13.1.2.

**Comment by oldalton** [comment]
@manojchandola, ADAL 2.2 is not supported on iOS 13. You need to use 2.7.14 or above on iOS 13. It will probably not fix your issue, just calling out that we don't support older ADALs with latest iOS versions.

Regarding you issue, do you have per app VPN by any chance? Some VPNs might have different settings for different apps and that's why you might be seeing a difference in behavior between your app and Safari. What happens if you disable VPN? Another idea is that your server behaves differently depending on the user agent. Also, ADAL 2.x uses a deprecated UIWebView and we recommend to use ADAL 4.x which uses WKWebView and is more closer to Safari in the underlying technology. 

@himanthmaddi, do you also have VPN involved in the flow by any chance? Can you provide more information on your setup?

**Comment by oldalton** [comment]
Did this ever get resolved? @manojchandola, @himanthmaddi

**Comment by himanthmaddi** [comment]
@oldalton I had fixed this by updating ADAL to 4.0.3. 

Note: Minimum OS version should be iOS 10 for this version of ADAL.

**Comment by oldalton** [comment]
Thanks for the update. Closing the issue, please reopen if needed.
