### ISSUE TITLE
ADAL with Intune

### ISSUE THREAD

**Issue by ledzep9012** [AzureAD/azure-activedirectory-library-for-objc#1521]
So technically my app should receive `ERROR_SERVER_PROTECTION_POLICY_REQUIRED` when calling `acquireTokenWithResource` as I've applied CA policies to the app. But `acquireTokenWithResource` responds with a valid `accessToken`. Am I missing something?

Thanks

**Comment by jasoncoolmax** [comment]
Hi @ledzep9012 , `ERROR_SERVER_PROTECTION_POLICY_REQUIRED` only happens in a specific scenario called True MAM. Could you please repro the issue and collect the correlation id, such that I can take a look? Thanks!

**Comment by ledzep9012** [comment]
Could you please explain the True MAM scenario, while I was awaiting feedback, I switched to MSAL for authentication as my app would also require access to `id_token` to verify with an API. I hope the true MAM scenario also exist in MSAL?

**Comment by ledzep9012** [comment]
Here's the Error that I'm getting
![WhatsApp Image 2020-02-20 at 6 10 00 PM](https://user-images.githubusercontent.com/19204594/74934722-d6e69d80-540c-11ea-8fd6-2632e3182b85.png)

**Comment by jasoncoolmax** [comment]
@ledzep9012 Thank you for providing the screenshot. 

If you apply the policy `Require approved client app`, users will only be able to login if the apps they are using is one of the following [apps](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-grant#require-approved-client-app).
(That's why you get the error in the screenshot you provided)

If you apply the policy `Require app protection policy (Preview)`, currently such a policy only applies to the following Microsoft [apps](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-grant#require-app-protection-policy). It  also means your app won't get those errors because your app is not in the list.

However, there are other CA policies that you can apply to your app, like `Require multi-factor authentication`, `Require device to be marked as compliant`, `Require Hybrid Azure AD joined device`, etc. 

Hopefully it helps :)

**Comment by ledzep9012** [comment]
@jasoncoolmax Thank you for providing much clarity on this. 
![image](https://user-images.githubusercontent.com/19204594/75323021-0f1d2e80-589a-11ea-80fb-b1bd57c86f58.png)
As you can see above, this is the policy which is blocking the user to sign in. The original question remains the same, how do enforce the user to register with Intune first and then proceed with normal authentication once this error `ERROR_SERVER_PROTECTION_POLICY_REQUIRED` or some other comes up. But this error is inside a webview and not very conclusive about the next steps, could you share your insights as to how to handle this?

**Comment by jasoncoolmax** [comment]
@ShruthiAchutha Will it be possible to share some instruction to enable Intune MAM protection policy for this app?

**Comment by ShruthiAchutha** [comment]
@ledzep9012 does your app integrate with Intune MAM SDK? https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios provides instructions for doing that. https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy has instructions on how you can create App Protection Policies and target them. Let me know if you plan on doing this and I can connect you to the right folks on my team to make sure your app needs that and is setup right.

**Comment by mipetriu** [comment]
Closing this issue, feel free to reopen.
