### ISSUE TITLE
Difference between Release 2x and 4x

### ISSUE THREAD

**Issue by AnilKumar09** [AzureAD/azure-activedirectory-library-for-objc#1527]
Hi,
Could someone please provide me the difference between
release 2x and 4x.

Thanks...
AK

**Comment by oldalton** [comment]
Hi. ADAL 2.x uses UIWebView on iOS which is now deprecated by Apple. ADAL 4.x uses WKWebView for both iOS and macOS. Apple now has announced that it will stop accepting uploads of apps using UIWebView. Therefore, we recommend everyone to use ADAL 4.x. 

However, if you're building the new app, you should be using our new MSAL library since ADAL itself will be deprecated shortly: https://github.com/AzureAD/microsoft-authentication-library-for-objc

Please let me know if you have additional questions.
