### ISSUE TITLE
ADALiOSBundle.bundle needs to be generated as ADALiOS.bundle (OSXUniversal branch)

### ISSUE THREAD

**Issue by HiKumar-MS** [AzureAD/azure-activedirectory-library-for-objc#300]
I noticed that the resource bundle generated by the ADAL project is “ADALiOSBundle.bundle” but the code that tries to load the resource bundle in the ADAL library is trying to load it as “ADALiOS.bundle”([ADAuthenticationBroker frameworkBundle]). The ADAL test app gets around this because it simply copies the storyboard files into the test app, instead of copying in the bundle and loading it from there.
This was fixed in master: to change ADALiOSBundle.bundle->ADALiOS.bundle: https://github.com/AzureAD/azure-activedirectory-library-for-objc/commit/b61bb11f7fc420d47c23b38111cc54f8f9a73726

**Comment by brandwe** [comment]
I thought it was no longer necessary to even include the storyboard files for ADAL anymore?

On Apr 23, 2015, at 1:04 PM, Himanshu Kumar <notifications@github.com<mailto:notifications@github.com>> wrote:


I noticed that the resource bundle generated by the ADAL project is “ADALiOSBundle.bundle” but the code that tries to load the resource bundle in the ADAL library is trying to load it as “ADALiOS.bundle”([ADAuthenticationBroker frameworkBundle]). The ADAL test app gets around this because it simply copies the storyboard files into the test app, instead of copying in the bundle and loading it from there.
This was fixed in master: to change ADALiOSBundle.bundle->ADALiOS.bundle: b61bb11<https://github.com/AzureAD/azure-activedirectory-library-for-objc/commit/b61bb11f7fc420d47c23b38111cc54f8f9a73726>
