### ISSUE TITLE
SSL issue with iOS 9 Beta

### ISSUE THREAD

**Issue by dangodb** [AzureAD/azure-activedirectory-library-for-objc#360]
We are getting the error below when trying to load ADAL in a iOS 9 beta emulator:

Status is AD_FAILED
Error Message is "An SSL error has occurred and a secure connection to the server cannot be made."

**Comment by brandwe** [comment]
iOS 9 forces connections that are using HTTPS to be TLS 1.2 to avoid recent vulnerabilities. In iOS 8 even unencrypted HTTP connections were supported, so that older versions of TLS didn't make any problems either. 

As a workaround, you can add this code snippet to your Info.plist:
<key>NSAppTransportSecurity</key>  
  <dict>  
  <key>NSAllowsArbitraryLoads</key>  
  <true/>  
  </dict>  

Thereby you're disabling the App Transport Security.

**Comment by brandwe** [comment]
Try again:

iOS 9 forces connections that are using HTTPS to be TLS 1.2 to avoid recent vulnerabilities. In iOS 8 even unencrypted HTTP connections were supported, so that older versions of TLS didn't make any problems either. 

As a workaround, you can add this code snippet to your Info.plist:
'''<key>NSAppTransportSecurity</key>  
  <dict>  
  <key>NSAllowsArbitraryLoads</key>  
  <true/>  
  </dict> '''

Thereby you're disabling the App Transport Security.

**Comment by RandalliLama** [comment]
@dangodb What authority are you passing in?  Is it an AAD authority or an ADFS authority?

**Comment by dangodb** [comment]
We are passing : https://login.windows.net/common/oauth2/authorize

**Comment by RandalliLama** [comment]
@brandwe If the problem is related to the TLS issue you raised above then I think we need to get a Wire Shark capture, or similar low level capture, of a repro.  We can then see what AAD is advertising as SSL/TLS versions and what iOS is advertising.  My guess is that there is that the intersection of those two sets is now the empty set.  I saw this exact issue with the Haskell TLS implementation.

**Comment by brandwe** [comment]
I wanted to give a quick update to the team  - although this workaround will unblock you - we do believe this is a bug with our server reporting TLS 1.0 when the required version by iOS is TLS 1.2. We *do* use TLS 1.2 at the protocol level, but the version being reported by the endpoint is wrong. This may be an issue with Azure VMs or our network. Our team has an incident going to figure this out.

I recommend that you use this only to unblock your testing until we get this fixed and then remove the workaround in your info.plist.

**Comment by RandalliLama** [comment]
@dangodb We have tracked down the issue to the TLS certificates being used by AAD services.  They are working on upgrading those certificates now.  In the meantime use the work around mentioned by @brandwe above.  Full documentation for that work around can be found here:

https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/

In the Exceptions section.

**Comment by dangodb** [comment]
Thanks

**Comment by vinnyp** [comment]
@RandalliLama is this fixed? Do you have an ETA? Our team (internal MSFT) is hitting this issue on iOS 9 GM / XCode 7.

**Comment by RandalliLama** [comment]
There is a partial fix in flight now.  However, it is a bigger problem than just AAD.  The next problem is going to be the CDN's that AAD depends on.  That means that web pages that require assets served by the CDN will not load correctly.  My recommendation is to use the work around for the time being.

**Comment by RandalliLama** [comment]
@vinnyp @dangodb This issue is fixed

**Comment by vinnyp** [comment]
@RandalliLama can you post a reference to which commit fixed this?

Also, when should we expect a new release?

**Comment by RandalliLama** [comment]
@vinnyp It's not a client side fix.  It was strictly server side.  The server deployed new certs that pass iOS 9 muster.  At this point you should find the issue fixed without any change to ADAL.
