### ISSUE TITLE
Resource owner flow not supported

### ISSUE THREAD

**Issue by dimkanewtown** [AzureAD/azure-activedirectory-library-for-objc#390]
Has the Resource owner flow been omitted from the iOS version of the library intentionally? The .NET version completely supports it. Thanks.

**Comment by vibronet** [comment]
It is by design. We do not recommend direct use of username and password, given the security implications of gathering and handling credentials in the app's code and the intrinsic limitations the approach entails (no support for guests and federation, no support for MSA, no support for multi factor auth, no support for consent prompts, etc). The .NET version of the library is also mean to develop command line apps or in general apps meant for headless scenarios, which is why we do support (but still not recommend) direct use of user credentials there. However such apps are not ins cope for any other platform, and the library surface reflects that.
