### ISSUE TITLE
ADAuthenticationRequest+AcquireAssertion.h is missing '#import "ADAuthenticationRequest.h'

### ISSUE THREAD

**Issue by martinpgrayson** [AzureAD/azure-activedirectory-library-for-objc#540]
As above. ADALiOS not building because of this missing import. Adding import locally fixed.

This is using 3.0.0-pre3

**Comment by RPangrle** [comment]
Why are you importing ADAuthenticationRequest in the first place? That's supposed to be a private header.

**Comment by spr-kevinmcmahon** [comment]
I had this issue too. It isn't that we're including the header or trying to use the feature. It is that after you upgrade (the cocoapod in my case) the entire project won't build because of the error above is being caused when the ADAL code is being compiled. I can probably put together a test case if you'd like but it was broken "out of the box" for me when I upgraded and should be easy to reproduce.
