### ISSUE TITLE
x86-64 build branch convergence-dev

### ISSUE THREAD

**Issue by ajjnix** [AzureAD/azure-activedirectory-library-for-objc#590]
I use inside swift project branch convergence-dev. And carthage can't work with static lib (only framework). 
I know what build have script for generate framework, but carthage don't know it.

So I build static lib and add it in project. But it only for arm7 and arm64 and I don't run it use simulator. Please add support x86-64 platform 

Also I watch other branch but it very different with convergence-dev

**Comment by RPangrle** [comment]
Xcode by default only builds binaries for device (ARM) or simulator (x86) and provides no-built in way for a "fat" binary that combines the two as you should never need to ship such a thing. Furthermore there are SDK differences between simulator and device, which is why the two end up in different build locations. If you're looking to use simulator builds you need to set that up separately with properly configured import paths.
