### ISSUE TITLE
ADAL should send haschrome=1 QP for all interactive requests

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/azure-activedirectory-library-for-objc#632]
ADAL should send haschrome=1 QP for all interactive requests. This will hide the back button the UI and developers will stop getting access_denied error when it was actually user_cancel.

**Comment by smudireddy** [comment]
if iOS agent ADAL module sends "haschrome=1" then cert based authentication failing with an error.
How to control/ignore from AD end ?

**Comment by smudireddy** [comment]
Hi Jasoncoolmax,

if native iOS app ADAL module sends "haschrome=1" then cert based authentication using ADFS failing with an error.
How to control/ignore this from AD end instead of setting 0 or removing it from ADAL sources ?. If there is no option to control it on AD then where we have to check on AD side which causing the Auth failure ?
