### ISSUE TITLE
NSURLErrorDomain -1200

### ISSUE THREAD

**Issue by nhart12** [AzureAD/azure-activedirectory-library-for-objc#667]
I'm getting logs from my app using ADALiOS vs 1.2.7 with the following error:

An SSL error has occurred and a secure connection to the server cannot be made. 
domain: NSURLErrorDomain
code: -1200

I have had the following in my info.plist since iOS 9 came out. Is it safe to remove this setting now?
`<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>`
This error seems to be intermittent and I cannot replicate in my local testing, so I don't know where to begin the debugging. The error is sometimes grouped with other network related errors, but seems unrelated. Doesn't the library use a cached token after initial login? I'm not sure why it is trying to reach out to the server so often.
The network connection was lost., code: -1005, domain: NSURLErrorDomain
The request timed out., code: -1001, domain: NSURLErrorDomain

**Comment by RPangrle** [comment]
Access tokens expire after 1 hr, so ADAL has to go back to the server if more then an hour has passed after you got the token. AAD itself is safe to use with app transport security but some federated endpoints might not be clean yet, removing the ATS exception could help flush some of those out :). There also are proxies out there that try to pierce SSL that can cause problems. We're looking at improving our SSL error logging so that more information is available in the logs, but you should upgrade to 2.2 so you will be in a better position to take advantage of that.

**Comment by nhart12** [comment]
Thanks, @RPangrle . I will work on updating to 2.2. Is there any way to extend the expiration?

**Comment by RPangrle** [comment]
There is some work happening to allow admins to set expiration times as they wish, but app developers have no control over the expiration behavior.

**Comment by nhart12** [comment]
Ok makes sense. Thanks. I'll close this since it sounds like you guys are aware and on top of it.
