### ISSUE TITLE
2.2.0.1 Calling Cancel before Acquire not working

### ISSUE THREAD

**Issue by nhart12** [AzureAD/azure-activedirectory-library-for-objc#681]
My iOS app has different environment settings and different AD's it hits per environment. When a user switches environments while a current webview auth session is active, I need to cancel any previous sessions and create a new AuthContext with different settings. This worked fine in 1.2.7 by calling             ADAuthenticationBroker.sharedInstance().cancel().

In 2.2.0 I call ADWebAuthController.cancelCurrentWebAuthSession() before setting up the new Auth context, but it seems that the cancel doesn't actually happen on the previous session until later on, so the new acquireTokenWithResource call always fails with the following message:

The user is currently prompted for credentials as result of another acquireToken request. Please retry the acquireToken call later.
Is there a better flow I can use to cancel and/or switch AD's on the fly like this?

**Comment by RPangrle** [comment]
The backing implementation of that cancel didn't change, we just renamed the API to make it more explicit as to what it does. There's never been a sure-fire mechanism for canceling a previous session in ADAL (after all if it wasn't web auth it wouldn't cancel anything at all). Nor has the cancel ever been synchronous. What *did* change was all the extraneous dispatch_asyncs that ADAL used to do but doesn't anymore. If I had to guess what's happening here is that it worked in 1.2.x as a side effect of some of the poorly written threading code in ADAL, and doesn't work now because ADAL only dispatches when it's necessary.

If you need to be able to rapid-fire web auths in such a manner I would recommend keeping a semaphore in your completion handler that you can wait on before making another acquire request.

**Comment by nhart12** [comment]
That's a great idea! I will test it out in the morning. Thanks for the quick response.

**Comment by nhart12** [comment]
Thanks this seems to be working. My code isn't as pretty as I'd like but its functional now.
