### ISSUE TITLE
ADALiOS target is no longer producing a libADALiOS.a file

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/azure-activedirectory-library-for-objc#756]

**Comment by 5fcgdaeb** [comment]
I am guessing this is the same issue.

We have been told to upgrade to version 2.2.5 or higher with the release of iOS10. However, we now can't release our app due to the error:

chown: /Users/XXX/Library/Developer/Xcode/DerivedData/XXXX-amrtjmthfmzhgndkjeqsrgbqkkax/Build/Intermediates/ArchiveIntermediates/Sales/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libADALiOS.a: No such file or directory
Command /usr/sbin/chown failed with exit code 1

Is there a workaround for this? The app should be released today.

**Comment by RPangrle** [comment]
You can link in the libADAL-core.a file as well.

**Comment by tsteele2013** [comment]
@RPangrle  Any chance you can update your README in Master? I just spent a few hours banging my head against the wall because I didn't know libADAL-core.a was a viable alternative to libADALiOS.a.
