### ISSUE TITLE
Sign-In issue - Calling principal cannot consent due to lack of permissions

### ISSUE THREAD

**Issue by krunalbhavsar** [AzureAD/azure-activedirectory-library-for-objc#812]
ADAL 2.2.8-dev iOS
Error - Calling principal cannot consent due to lack of permissions

Please update

**Comment by RPangrle** [comment]
1. Please use released versions of ADAL. The latest release of ADAL is 2.2.6, you can always use the releases page to find the latest: https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases

2. The error described is due to a combination of that tenant and your application listing. You will need to the tenant administrator to allow your app.
