### ISSUE TITLE
Logic Error in ADWebRequest.h

### ISSUE THREAD

**Issue by admeister** [AzureAD/azure-activedirectory-library-for-objc#985]
Xcode is reporting a logic error in ADWebRequest.h at line 55 (in checked out tag 2.4.1)

`@property (copy, nonatomic)             NSMutableDictionary *headers;`

ADAL/src/request/ADWebRequest.h:55:1: Property of mutable type 'NSMutableDictionary' has 'copy' attribute; an immutable object will be stored instead

**Comment by oldalton** [comment]
Thanks for reporting this issue. I confirm that there's a problem and it has actually been already fixed in [dev branch](https://github.com/AzureAD/azure-activedirectory-library-for-objc/commit/54a83e0e06f3cae9e2371451a42a26e73d05a302#diff-298c801c6f46cf1f876980415d02c59b). The fix will be included in the next ADAL release.
